name: Bug report
description: Report a bug to help us improve
labels: ["type:bug"]
body:
  - type: checkboxes
    attributes:
      label: Checks
      options:
        - label: I have searched existing issues
          required: true
        - label: I have run `pnpm reset` locally and reproduced the issue
          required: false
  - type: textarea
    attributes:
      label: Description
      description: Clear and concise description of the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Provide minimal steps/code that reproduce the issue
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behavior / logs
      description: Paste relevant logs, error messages, screenshots
    validations:
      required: true
  - type: input
    attributes:
      label: Affected package(s)
      placeholder: e.g., @swissjs/core, @swissjs/cli
  - type: dropdown
    attributes:
      label: Area
      options:
        - area:core
        - area:cli
        - area:plugins
        - area:docs
        - area:devtools
        - area:vscode
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Priority
      options:
        - priority:high
        - priority:medium
        - priority:low
    validations:
      required: false
